# NOTE: See https://github.com/traefik/traefik-helm-chart/blob/master/traefik/values.yaml
# NOTE: DO NOT PUT SECRET VALUES IN THIS FILE! THIS FILE WILL BE MERGED CAN BE
#       OVERWRITTEN IN ``k8s.py``. ALSO, TRY TO PROVIDE REFERENCES TO K8s 
#       secrets instead.
additionalArguments:
  # - --providers.kubernetescrd
  # - --certificatesresolvers.porkbun.acme.tlschallenge
  # - --entrypoints.websecure.http.tls.certresolver=porkbun
  - --entrypoints.websecure.http.tls.domains[0].main=acederberg.io
  - --entrypoints.websecure.http.tls.domains[0].sans=*.acederberg.io

# ingressRoute:
#   dashboard: 
#     enabled: True # default
#     matchRule: Host(`traefik.acederberg.io`)
#     entryPoints: ["websecure"]
#     middlewares:
#       - name: traefik-dashboard-auth
#       

providers:
  kubernetesCRD:
    allowCrossNamespace: true


ports: 
  traefik:
    port: 9000 # default
    exposedPort: 9000 # default
  web:
    redirectTo: 
      port: websecure
  websecure:
    port: 8443 # default
    exposedPort: 443 # default
tls:
  enabled: true

# NOTE: See https://github.com/traefik/traefik-helm-chart/blob/master/EXAMPLES.md
certResolvers:
  letsencrypt: 
    email: adrn.cederberg123@gmail.com
    dnsChallenge:
      provider: porkbun
    storage: /data/acme.json


# env:
#   - name: PORKBUN_API_KEY
#     valueFrom:
#       secretKeyRef:
#         name: porkbun
#         key: porkbun_api_key
#   - name: PORKBUN_SECRET_API_KEY
#     valueFrom:
#       secretKeyRef:
#         name: porkbun
#         key: porkbun_secret_key
#

deployment:
  initContainers:
    - name: volume-permissions
      image: busybox:latest
      command: ["sh", "-c", "touch /data/acme.json; chmod -v 600 /data/acme.json"]
      volumeMounts:
      - mountPath: /data
        name: data
