FROM python:3.12 AS base

RUN useradd -d /home/pipelines pipelines \
  && mkdir /home/pipelines

COPY . /home/pipelines
RUN chown -R pipelines:pipelines /home/pipelines

USER pipelines
WORKDIR /home/pipelines
RUN pip install .

ENTRYPOINT ["bash"]


# --------------------------------------------------------------------------- #

FROM base AS pipeline

RUN pip install .[pipelines]



FROM pipeline AS pipeline-test

RUN pip install .[test]


# --------------------------------------------------------------------------- #
# FROM base AS pulumi
