---
apiVersion: v1
kind: Namespace
metadata:
  name: error-pages
  labels:
    acederberg.io/tier: base
    acederberg.io/from: pulumi
    acederberg.io/component: error-pages
---
apiVersion: apps/v1
kind: Deployment
metadata: &err-metadata
  name: error-pages
  namespace: traefik
  labels: &err-metadata-labels
    acederberg.io/tier: base
    acederberg.io/from: pulumi
    acederberg.io/component: error-pages
spec:
  replicas: 1
  selector:
    matchLabels:
      <<: *err-metadata-labels
  template:
    metadata: *err-metadata 
    spec:
      containers:
        - name: error-pages
          image: ghcr.io/tarampampam/error-pages
          readinessProbe:
            httpGet: 
              path: /500.html
              port: 8080
          ports:
            - containerPort: 8080
#
---
apiVersion: v1
kind: Service
metadata:
  name: error-pages
  namespace: traefik
  labels: 
    acederberg.io/tier: base
    acederberg.io/from: pulumi
    acederberg.io/component: error-pages
spec:
  type: ClusterIP
  ports:
    - name: err-pages-http
      port: 8080
      targetPort: 8080
  selector:
    acederberg.io/tier: base
    acederberg.io/from: pulumi
    acederberg.io/component: error-pages
  
#
---
apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: error-pages
  namespace: traefik
  labels: 
    acederberg.io/tier: base
    acederberg.io/from: pulumi
    acederberg.io/component: error-pages
spec:
  errors:
    status:
      - "400-499"
      - "500-599"
    query: /{status}.html
    service:
      namespace: traefik
      name: error-pages
      port: 8080
        
        
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: error-pages
  namespace: traefik
  labels:
    acederberg.io/tier: base
    acederberg.io/from: pulumi
    acederberg.io/component: error-pages
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: HOST(`errors.acederberg.io`)
    middlewares:
    - name: error-pages
      namespace: traefik
    services:
    - kind: Service
      name: error-pages
      namespace: traefik
      port: 8080
  tls:
    certResolver: letsencrypt
#

